### ISSUE TITLE
Cannot load the model

### ISSUE THREAD

**Issue by levanhieu-git** [dxaen/percival#1]
Hi, I am unable to load the pytorch model when opening percival chromium browser. When looking at the code, it looks like GetModelPath is looking for a Sq2.json file to be used with fdeep.load_model.

Am i missing something here?

**Comment by dxaen** [comment]
Sorry for the delay. Here it is 9b079c582b602a301e0753283b58d4325982bfb5

**Comment by levanhieu-git** [comment]
thank you!
